# Aprendizaje Automático
## Tercera práctica guiada
---
Para la tercera práctica del curso de aprendizaje automático, se utilizará el mismo conjunto de datos que pertenece al repositorio especial de Machine Learning de la [UCI](https://archive.ics.uci.edu/ml). El conjunto de datos se llama "Adult" y toda la información correspondiente al mismo se encuentra [aquí](https://archive.ics.uci.edu/ml/datasets/Adult).

---
### Máquinas de Vectores de Soporte, K-Vecinos más cercanos y Análisis de discriminante lineal y cuadrático.

###### En principio, importamos todas las librerías necesarias para trabajar Aprendizaje Automático con Python y Sci-kit learn

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
import itertools
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree
from sklearn import svm
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier
import io
import requests


###### Luego procedemos a importar los datos de entrenamiento y eliminar los valores faltantes, además de convertir los valores categóricos a enteros.

In [2]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
ds_ = pd.read_csv(url, header=None, na_values=" ?")
ds = ds_.dropna()
ds = ds.rename(columns = {ds.columns.values[14]:'C'}) # Cambiamos el nombre de la última columna por "C" de clase
le = preprocessing.LabelEncoder() # Label encoder de sci-kit
ds = ds.apply(le.fit_transform) # Convertimos los valores de object a int
class_names = ['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education-num', 'Marital-status', 'Occupation',
              'Relationship', 'Race', 'Sex', 'Capital-gain', 'Capital-loss', 'Hpw', 'Country']
ds


0  1      2   3   4  5   6  7  8  9   10  11  12  13  C
0      22  5   2491   9  12  4   0  1  4  1   24   0  39  38  0
1      33  4   2727   9  12  2   3  0  4  1    0   0  12  38  0
2      21  2  13188  11   8  0   5  1  4  1    0   0  39  38  0
3      36  2  14354   1   6  2   5  0  2  1    0   0  39  38  0
4      11  2  18120   9  12  2   9  5  2  0    0   0  39   4  0
5      20  2  16567  12  13  2   3  5  4  0    0   0  39  38  0
6      32  2   7982   6   4  3   7  1  2  0    0   0  15  22  0
7      35  4  12746  11   8  2   3  0  4  1    0   0  44  38  1
8      14  2   1225  12  13  4   9  1  4  0  104   0  49  38  1
9      25  2   7908   9  12  2   3  0  4  1   78   0  39  38  1
10     20  2  16411  15   9  2   3  0  2  1    0   0  76  38  1
11     13  5   6629   9  12  2   9  0  1  1    0   0  39  18  1
12      6  2   5399   9  12  4   0  3  4  0    0   0  29  38  0
13     15  2  12364   7  11  4  11  1  2  1    0   0  49  38  0
15     17  2  14951   5   3  2  13  0  0  1    0   0  44  25  0
16      8  4   9507  11   8  4   4  3  4  1    0   0  34  38  0
17     15  2  10533  11   8  4   6  4  4  1    0   0  39  38  0
18     21  2    292   1   6  2  11  0  4  1    0   0  49  38  0
19     26  4  16831  12  13  0   3  4  4  0    0   0  44  38  1
20     23  2  11280  10  15  2   9  0  4  1    0   0  59  38  1
21     37  2  17134  11   8  5   7  4  2  0    0   0  19  38  0
22     18  0   2457   6   4  2   4  0  2  1    0   0  39  38  0
23     26  2   4963   1   6  2  13  0  4  1    0  54  39  38  0
24     42  2   4309  11   8  0  12  4  4  0    0   0  39  38  0
25     39  1  13274   9  12  2  12  0  4  1    0   0  39  38  1
26      2  2   8667  11   8  4   2  3  4  1    0   0  39  38  0
28     22  2  18795  11   8  0   3  1  4  1    0   0  76  38  0
29     32  2  11265  11   8  2   2  0  4  1    0   0  39  38  0
30      6  1  10970   7  11  4  10  1  4  1    0   0  51  38  0
31      3  2  15818  15   9  4  11  3  2  1    0   0  43  38  0
...    .. ..    ...  ..  .. ..  .. .. .. ..  ...  ..  ..  .. ..
32526  15  2  12879   0   5  2  13  0  4  1    0   0  39  38  0
32527   5  2  12252  15   9  4   0  3  4  1    0   0  39  38  0
32528  14  2  16847  11   8  2   6  5  4  0    0   0  39  38  0
32529  12  2   5649  11   8  5  11  4  4  0    0   0  34  38  0
32532  17  2  12317  10  15  2   9  0  4  1    0   0  59  38  1
32533  37  2  18108   9  12  2   3  0  1  1    0   0  49  23  1
32534  20  2   9751  15   9  0   0  4  4  0    0   0  38  38  0
32535   5  2  17787   2   7  4  10  3  2  1    0   0  34  38  0
32536  17  2   7984   9  12  4   3  1  4  0    0   0  54  38  1
32537  13  2  18343  11   8  4   2  1  2  1    0   0  45  38  0
32538  21  2   6502   9  12  0   9  4  2  0  106   0  44  38  1
32540  28  5  15249  11   8  5   0  3  4  0    0   0  39  38  0
32543  28  1   5171   7  11  0   9  4  4  0    0   0  47  38  0
32544  14  2  11894  12  13  0   7  1  3  0    0   0  29  38  0
32545  22  1   4519   7  11  2   0  5  4  0    0   0  19  38  1
32546  20  2  11741   7  11  0  12  1  4  0    0   0  39  38  0
32547  26  2  15617  11   8  2   6  0  4  1    0   0  39  25  0
32548  48  4   3556  14  14  4   9  1  4  1    7   0  59  38  0
32549  26  5  15404  15   9  0   0  2  4  0    0   0  39  38  0
32550  26  4    214  15   9  2   2  0  4  1    0   0  49  38  0
32551  15  2    648   0   5  2   5  0  0  1    0   0  39  38  0
32552  26  2   2802   8  10  2  11  0  4  1    0   0  44  38  0
32553  15  2   4886  12  13  4  12  1  1  1    0   0  10  35  0
32554  36  2  17708  12  13  2   3  0  4  1    0   0  39  38  1
32555   5  2  17375  15   9  4  10  1  4  1    0   0  39  38  0
32556  10  2  15471   7  11  2  12  5  4  0    0   0  37  38  0
32557  23  2   7555  11   8  2   6  0  4  1    0   0  39  38  1
32558  41  2   7377  11   8  6   0  4  4  0    0   0  39  38  0
32559   5  2  12060  11   8  4   0  3  4  1    0   0  19  38  0
32560  35  3  16689  11   8  2   3  5  4  0  107   0  39  38  1

[30162 rows x 15 columns]

###### Importamos los datos de prueba de la misma manera que importamos los datos de entrenamiento.

In [4]:
urltest = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test"
test_ = pd.read_csv(urltest, skiprows=1, header=None, na_values=" ?")
test = test_.dropna()
test = test.rename(columns = {test.columns.values[14]:'C'}) # Cambiamos el nombre de la última columna por "C" de clases = test.apply(le.fit_transform) # Convertimos los valores de object a int
test = test.apply(le.fit_transform) # Convertimos los valores de object a int
test

0  1      2   3   4  5   6  7  8  9   10  11  12  13  C
0       8  2   8315   1   6  4   6  3  2  1    0   0  39  37  0
1      21  2   1754  11   8  2   4  0  4  1    0   0  49  37  0
2      11  1  10750   7  11  2  10  0  4  1    0   0  39  37  1
3      27  2   4780  15   9  2   6  0  2  1   87   0  39  37  1
5      17  2   7091   0   5  4   7  1  4  1    0   0  29  37  0
7      46  4   2342  14  14  2   9  0  4  1   44   0  31  37  1
8       7  2  11153  15   9  4   7  4  4  0    0   0  39  37  0
9      38  2   2361   5   3  2   2  0  4  1    0   0   9  37  0
10     48  2   6199  11   8  2   6  0  4  1   77   0  39  37  1
11     19  0   7773   9  12  2   0  0  4  1    0   0  39  37  0
12      9  2   1548  11   8  4   0  1  4  0    0   0  38  37  0
14     31  2   9790  11   8  2   6  0  4  1   44   0  47  37  1
15     26  2  10882  12  13  2   3  0  4  1    0   0  49  37  1
16      3  5  11624  15   9  4   7  3  4  1    0   0  24  37  0
17     26  2   3425  11   8  2   0  5  4  0    0   0  29  37  0
18     20  2   1093  11   8  6   6  4  4  0    0   0  19  37  0
20     17  2   2508   9  12  2  12  0  4  1    0   0  46  37  1
21     17  2   8718  15   9  4   7  3  2  0    0   0  34  37  0
23      8  2   8107   9  12  4   9  1  4  1    0   0  42  27  0
24      8  2   7488   9  12  2   9  0  4  1    0   0  39  37  0
25     28  4  11575  11   8  2   2  0  4  1   84   0  84  37  1
26      5  2   8648  11   8  4   0  3  4  1    0   0  19  37  0
27      6  2   3666  11   8  5   6  4  2  1    0   0  53  37  0
28     37  2   2092  11   8  2   2  0  4  1    0   0  34  37  0
29     15  4   2574  15   9  4   9  1  4  1    0   0  59  37  0
30     29  5   2430  15   9  2   3  0  2  1   87   0  37  37  1
31     39  4   6335   1   6  6   7  4  4  0    0   0  49  37  0
32      7  4   6452   9  12  4  11  1  4  1    0   0  49  37  0
33      6  1   9267  15   9  2  10  0  4  1    0   0  39  37  0
34      9  2    640  11   8  0   3  4  4  0    0   0  39  37  0
...    .. ..    ...  ..  .. ..  .. .. .. ..  ...  ..  ..  .. ..
16248   8  2   8822  11   8  0   6  1  2  1    0   0  39  37  0
16249  14  2   2709  11   8  4   6  1  4  1    0   0  39  37  0
16250  32  3   1436  11   8  2   3  0  4  1    0   0  39   1  1
16252  43  2   3009   8  10  2   9  0  4  1   87   0  39  37  1
16253  22  2   8429   9  12  4  12  1  4  0    0  27  39  37  0
16254  21  2   4270  12  13  2   9  0  4  1    0   0  49  37  1
16255  26  1     51  12  13  2   3  0  4  1    0  42  49  37  1
16256   6  2   1870  11   8  4   6  3  4  1    0   0  39  37  0
16257  56  3   4751  15   9  0   3  1  4  0    0   0  39  37  0
16258  18  2   5733  15   9  2  10  0  4  1    0   0  39  37  0
16259  49  2  10860  11   8  6  11  2  4  0    0   0   7  37  0
16260  10  2  11565  15   9  4  11  1  4  0    0   0  44  37  0
16261  23  2   7310  14  14  2   9  0  4  1  101   0  54  37  1
16262  34  2   1563  11   8  2   2  0  4  1    0   0  39  37  0
16263   5  2   9562  15   9  4   2  3  4  1    0   0  39  37  0
16264  47  4   3745  11   8  6   4  1  4  1    0   0  31  37  0
16266  38  2   8237  11   8  5   8  1  4  0    0   0  31  37  0
16267  21  2   8985   8  10  4   0  4  2  0    0   0  39  37  0
16268  41  2  10042   7  11  0   9  1  4  1    0   0  35  37  0
16269  15  2   5485  11   8  2   5  0  4  1    0   0  39  37  0
16270  31  2   9901  11   8  2   0  0  4  1    0   0  39  37  0
16271  44  2   1749  11   8  2  11  0  4  1    0   0  47  37  0
16272  14  2  11608  11   8  2   2  0  4  1    0   0  39  37  0
16273   8  2  10942  11   8  4   7  3  4  0    0   0  39  37  0
16274  31  1  10923  12  13  0   7  1  4  1    0   0  39  37  0
16275  16  2   8927   9  12  4   9  3  4  1    0   0  39  37  0
16276  22  2   7893   9  12  0   9  1  4  0    0   0  35  37  0
16278  21  2  11193   9  12  2   9  0  4  1    0   0  49  37  0
16279  27  2   1593   9  12  0   0  3  1  1   73   0  39  37  0
16280  18  3   6062   9  12  2   3  0  4  1    0   0  59  37  1

[15060 rows x 15 columns]

###### En este taller se debe extraer aleatoriamente un 10% de los datos del conjunto de entrenamiento. Este subconjunto constituirá el conjunto de validación, que se usará para estimar los valores de los parámetros en las técnicas que así lo requieran. Todas las técnicas deberán entrenarse con el mismo conjunto de entrenamiento para que sea posible comparar sus desempeños. En la siguiente celda, se divide el conjunto de entrenamiento como se enunció.

In [14]:
x_train = ds.drop('C', axis = 1)
y_train = ds['C']

x_test = test.drop('C', axis = 1)
y_test = test['C']

from collections import Counter

x_strainval, x_stestval, y_strainval, y_stestval = train_test_split(x_train, y_train, test_size = 0.1, random_state=None)
print('Original dataset shape trainval {}'.format(Counter(y_strainval)))
print('Original dataset shape testval {}'.format(Counter(y_stestval)))
x_train

Original dataset shape trainval Counter({0: 20370, 1: 6775})
Original dataset shape testval Counter({0: 2284, 1: 733})


0   1      2   3   4   5   6   7   8   9    10  11  12  13
0      22   5   2491   9  12   4   0   1   4   1   24   0  39  38
1      33   4   2727   9  12   2   3   0   4   1    0   0  12  38
2      21   2  13188  11   8   0   5   1   4   1    0   0  39  38
3      36   2  14354   1   6   2   5   0   2   1    0   0  39  38
4      11   2  18120   9  12   2   9   5   2   0    0   0  39   4
5      20   2  16567  12  13   2   3   5   4   0    0   0  39  38
6      32   2   7982   6   4   3   7   1   2   0    0   0  15  22
7      35   4  12746  11   8   2   3   0   4   1    0   0  44  38
8      14   2   1225  12  13   4   9   1   4   0  104   0  49  38
9      25   2   7908   9  12   2   3   0   4   1   78   0  39  38
10     20   2  16411  15   9   2   3   0   2   1    0   0  76  38
11     13   5   6629   9  12   2   9   0   1   1    0   0  39  18
12      6   2   5399   9  12   4   0   3   4   0    0   0  29  38
13     15   2  12364   7  11   4  11   1   2   1    0   0  49  38
15     17   2  14951   5   3   2  13   0   0   1    0   0  44  25
16      8   4   9507  11   8   4   4   3   4   1    0   0  34  38
17     15   2  10533  11   8   4   6   4   4   1    0   0  39  38
18     21   2    292   1   6   2  11   0   4   1    0   0  49  38
19     26   4  16831  12  13   0   3   4   4   0    0   0  44  38
20     23   2  11280  10  15   2   9   0   4   1    0   0  59  38
21     37   2  17134  11   8   5   7   4   2   0    0   0  19  38
22     18   0   2457   6   4   2   4   0   2   1    0   0  39  38
23     26   2   4963   1   6   2  13   0   4   1    0  54  39  38
24     42   2   4309  11   8   0  12   4   4   0    0   0  39  38
25     39   1  13274   9  12   2  12   0   4   1    0   0  39  38
26      2   2   8667  11   8   4   2   3   4   1    0   0  39  38
28     22   2  18795  11   8   0   3   1   4   1    0   0  76  38
29     32   2  11265  11   8   2   2   0   4   1    0   0  39  38
30      6   1  10970   7  11   4  10   1   4   1    0   0  51  38
31      3   2  15818  15   9   4  11   3   2   1    0   0  43  38
...    ..  ..    ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..
32526  15   2  12879   0   5   2  13   0   4   1    0   0  39  38
32527   5   2  12252  15   9   4   0   3   4   1    0   0  39  38
32528  14   2  16847  11   8   2   6   5   4   0    0   0  39  38
32529  12   2   5649  11   8   5  11   4   4   0    0   0  34  38
32532  17   2  12317  10  15   2   9   0   4   1    0   0  59  38
32533  37   2  18108   9  12   2   3   0   1   1    0   0  49  23
32534  20   2   9751  15   9   0   0   4   4   0    0   0  38  38
32535   5   2  17787   2   7   4  10   3   2   1    0   0  34  38
32536  17   2   7984   9  12   4   3   1   4   0    0   0  54  38
32537  13   2  18343  11   8   4   2   1   2   1    0   0  45  38
32538  21   2   6502   9  12   0   9   4   2   0  106   0  44  38
32540  28   5  15249  11   8   5   0   3   4   0    0   0  39  38
32543  28   1   5171   7  11   0   9   4   4   0    0   0  47  38
32544  14   2  11894  12  13   0   7   1   3   0    0   0  29  38
32545  22   1   4519   7  11   2   0   5   4   0    0   0  19  38
32546  20   2  11741   7  11   0  12   1   4   0    0   0  39  38
32547  26   2  15617  11   8   2   6   0   4   1    0   0  39  25
32548  48   4   3556  14  14   4   9   1   4   1    7   0  59  38
32549  26   5  15404  15   9   0   0   2   4   0    0   0  39  38
32550  26   4    214  15   9   2   2   0   4   1    0   0  49  38
32551  15   2    648   0   5   2   5   0   0   1    0   0  39  38
32552  26   2   2802   8  10   2  11   0   4   1    0   0  44  38
32553  15   2   4886  12  13   4  12   1   1   1    0   0  10  35
32554  36   2  17708  12  13   2   3   0   4   1    0   0  39  38
32555   5   2  17375  15   9   4  10   1   4   1    0   0  39  38
32556  10   2  15471   7  11   2  12   5   4   0    0   0  37  38
32557  23   2   7555  11   8   2   6   0   4   1    0   0  39  38
32558  41   2   7377  11   8   6   0   4   4   0    0   0  39  38
32559   5   2  12060  11   8   4   0   3   4   

###### Teniendo el subconjunto de validación, se entrenarán varias SVM con el fin de poder estimar cuál es la que mejor rendimiento muestra dependiendo de los distintos parámetros que se pueden ajustar para cada una.

A continuación se estimará qué parámetro C es el que mejor se comporta con las SVM.

In [11]:
########################################################################
#################### Linear SVM C=1.0 ##################################

SVM1 = svm.LinearSVC(dual=False)
SVM1.fit(x_strainval, y_strainval)

SVM1_predict = SVM1.predict(x_stestval)

print("\n############## Accuracy Linear SVM C=1.0 ##################")
print(metrics.accuracy_score(y_stestval, SVM1_predict))
print(metrics.confusion_matrix(y_stestval, SVM1_predict))

########################################################################
#################### Linear SVM C=5.0 ##################################

SVM5 = svm.LinearSVC(dual=False, C=5.0)
SVM5.fit(x_strainval, y_strainval)

SVM5_predict = SVM5.predict(x_stestval)

print("\n############## Accuracy Linear SVM C=5.0 ##################")
print(metrics.accuracy_score(y_stestval, SVM5_predict))
print(metrics.confusion_matrix(y_stestval, SVM5_predict))

########################################################################
#################### Linear SVM C=10.0 ##################################

SVM10 = svm.LinearSVC(dual=False, C=10.0)
SVM10.fit(x_strainval, y_strainval)

SVM10_predict = SVM10.predict(x_stestval)

print("\n############## Accuracy Linear SVM C=10.0 ##################")
print(metrics.accuracy_score(y_stestval, SVM10_predict))
print(metrics.confusion_matrix(y_stestval, SVM10_predict))

########################################################################
#################### Linear SVM C=50.0 ##################################

SVM50 = svm.LinearSVC(dual=False, C=50.0)
SVM50.fit(x_strainval, y_strainval)

SVM50_predict = SVM50.predict(x_stestval)

print("\n############## Accuracy Linear SVM C=50.0 ##################")
print(metrics.accuracy_score(y_stestval, SVM50_predict))
print(metrics.confusion_matrix(y_stestval, SVM50_predict))

########################################################################
#################### Linear SVM C=50.0 ##################################

SVM50 = svm.LinearSVC(dual=False, C=500.0)
SVM50.fit(x_strainval, y_strainval)

SVM50_predict = SVM50.predict(x_stestval)

print("\n############## Accuracy Linear SVM C=50.0 ##################")
print(metrics.accuracy_score(y_stestval, SVM50_predict))
print(metrics.confusion_matrix(y_stestval, SVM50_predict))
x_stestval


############## Accuracy Linear SVM C=1.0 ##################
0.799469671859463
[[2154  107]
 [ 498  258]]

############## Accuracy Linear SVM C=5.0 ##################
0.799469671859463
[[2154  107]
 [ 498  258]]

############## Accuracy Linear SVM C=10.0 ##################
0.799469671859463
[[2154  107]
 [ 498  258]]

############## Accuracy Linear SVM C=50.0 ##################
0.799469671859463
[[2154  107]
 [ 498  258]]

############## Accuracy Linear SVM C=50.0 ##################
0.799469671859463
[[2154  107]
 [ 498  258]]


0   1      2   3   4   5   6   7   8   9    10  11  12  13
22434  28   2   8662  12  13   0   9   1   4   1    0   0  39  38
4211    4   2  14871  11   8   2   4   0   4   1    0   0  39  38
13615   0   2  11248   1   6   4  11   4   4   0    0   0  11  30
6261   24   2  10595  11   8   5   0   4   4   0    0   0  39  38
13202  20   2   4206   9  12   2   9   0   4   1    0   0  54  38
14082   9   1  14790  11   8   2  10   0   4   1   49   0  39  38
27397  15   1   4762   9  12   0   9   4   4   0    0   0  34  38
1981   32   0   8661  11   8   2   0   0   4   1    0   0  39  38
3848   11   2  16473  15   9   5  12   4   4   1    0   0  39  38
27413  38   2   4826  14  14   2   3   0   4   1  117   0  39  38
32430  44   4   1437   5   3   2   4   0   4   1    0   0  55  38
17095  30   2   3415  11   8   2  10   5   2   0    0   0  39  38
13423  19   1   4371   9  12   4  10   1   4   1    0   0  59  38
18529  13   4    457   7  11   0   2   1   4   1    0   0  49  38
28451  17   2   4200  15   9   2   2   0   4   1    0   0  49  38
23183  22   1   3007  11   8   2   2   0   4   1    0   0  39  38
24745  21   2  13021  11   8   5  10   1   2   1    0   0  39  38
20678   1   2  14936  15   9   4   7   3   4   1    0   0  39  38
5375   14   0   6711   9  12   4   3   1   2   0    0   0  39  38
17426  21   4  14847   9  12   2   0   5   4   0    0   0  27  38
13438  12   2   6877   9  12   4  11   3   4   1    0   0  39  38
12163  47   1   3330   8  10   2   3   0   4   1    0   0  39  38
24708  23   4   9630   9  12   2   2   0   4   1    0   0  29  38
15779  36   5  16430  11   8   0   3   1   4   1    0  10  39  38
29117  17   2  16671  15   9   2   3   0   4   1    0   0  54  38
21137  17   2  13070  15   9   2   2   0   4   1    0   0  39  38
3296    7   2   1623  11   8   2  13   0   4   1    0   0  44  38
8194    5   2  10792  15   9   4  12   3   4   1    0   0  39  38
15749  32   0   5856   9  12   2   9   0   4   1    0   0  39  38
18069  23   2   7335  11   8   0   5   1   4   0    0   0  47  38
...    ..  ..    ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..
25017  49   2   9276  15   9   0   0   1   4   0    0   0  19  38
28104  33   2  10212  11   8   6  11   4   4   0    0   0  39  38
25907   4   2  12930  15   9   4   9   3   4   0    0   0   7  38
31362   2   2   8029  11   8   4  11   3   4   1    0   0  37  38
13144  20   2  11320   1   6   2   2   0   4   1    0   0  24  38
22433  29   2   9878  11   8   2   6   0   2   1    0   0  39  38
15608  11   2  10902   9  12   4   9   3   4   0    0  20  39  38
29957  18   4  14770   9  12   2   2   0   4   1    0   0  44  38
23003  13   2   8753  11   8   4   6   3   4   1    0   0  59  38
19595  34   2   2905   9  12   2   0   5   4   0   93   0  19  38
10430  17   2   6790  11   8   4  11   3   4   0    0   0  39  38
21416  33   1   3143  15   9   2   2   0   4   1    0   0  39  38
24997  16   2  16327  11   8   0   2   3   4   0    0   0  41  38
20091  10   5     82  11   8   4  13   1   0   1    0   0  37  38
30976  31   2   1378   7  11   0   0   4   4   0    0   0  39  38
25699   9   2   3238  15   9   2  13   0   4   1   90   0  54  38
18682  26   4   6857   2   7   2  13   0   4   1    0   0  59  38
10865   7   2  19698   9  12   4  12   3   4   1    0   0  39  38
13330  47   2  13568   3   1   0   8   1   4   0    0   0  11  38
19984  19   2  18923   1   6   2   6   0   4   1    0   0  39  38
12241  11   2  19425   1   6   2   2   1   4   1    0   0  59  38
9392   29   2   7639  12  13   2   3   0   4   1    0   0  49  38
6031   44   3  13920   9  12   5  11   1   4   0    0   0  29  38
8283   21   2  17833   8  10   2   3   0   4   1    0   0  44  38
10970   4   2   8900  11   8   4  11   3   4   0    0   0  29  38
18413  71   2  17465   9  12   4   9   3   4   0    0   0   9  38
18210  14   2  14707  15   9   2   2   0   4   1   67   0  49  38
31029  14   2  13374  15   9   4   7   1   4   1    0   0  29  38
17232  26   2   2199  15   9   2   0   0   4   

###### Claramente al variar el parámetro C no se encontró cambio alguno en el rendimiento de la SVM Lineal. Ahora, se entrenarán 2 SVM con funciones kernel distintas para evaluar cuál parametro arroja los mejores resultados con la partición previa que se obtuvo.

In [6]:
########################################################################
########################### RBF SVM ####################################

SVMrbf = svm.SVC(kernel='rbf')
SVMrbf.fit(x_strainval, y_strainval)

SVMrbf_predict = SVMrbf.predict(x_stestval)

print("\n############## Accuracy SVM RBF ##################")
print(metrics.accuracy_score(y_stestval, SVMrbf_predict))
print(metrics.confusion_matrix(y_stestval, SVMrbf_predict))

########################################################################
########################## Sigmoid SVM #################################

SVMsigmoid = svm.SVC(kernel='sigmoid')
SVMsigmoid.fit(x_strainval, y_strainval)

SVMsigmoid_predict = SVMsigmoid.predict(x_stestval)

print("\n############## Accuracy SVM Sigmoid ##################")
print(metrics.accuracy_score(y_stestval, SVMsigmoid_predict))
print(metrics.confusion_matrix(y_stestval, SVMsigmoid_predict))


############## Accuracy SVM RBF ##################
0.7494199535962877
[[2257    2]
 [ 754    4]]

############## Accuracy SVM Sigmoid ##################
0.7487570434206166
[[2259    0]
 [ 758    0]]


###### La SVM con kernel lineal obtuvo un mejor accuracy y por tal razón será usada para entrenar el clasificador y posteriormente evaluarlo con los datos originales de prueba. En la siguiente porción de código, entrenamos el clasificador y realizamos la respectiva predicción. Además, evaluamos el desempeño del clasificador teniendo en cuenta las métricas que provee el reporte de clasificación de sklearn.

In [13]:
########################################################################
#################### Linear SVM FINAL ##################################

SVM = svm.LinearSVC(dual=False)
SVM.fit(x_train, y_train)

SVM_predict = SVM.predict(x_test)

print("\n############## Accuracy Linear SVM FINAL ##################")
print(metrics.accuracy_score(y_test, SVM_predict))
print(metrics.confusion_matrix(y_test, SVM_predict))
x_test


############## Accuracy Linear SVM FINAL ##################
0.80199203187251
[[10697   663]
 [ 2319  1381]]


0   1      2   3   4   5   6   7   8   9    10  11  12  13
0       8   2   8315   1   6   4   6   3   2   1    0   0  39  37
1      21   2   1754  11   8   2   4   0   4   1    0   0  49  37
2      11   1  10750   7  11   2  10   0   4   1    0   0  39  37
3      27   2   4780  15   9   2   6   0   2   1   87   0  39  37
5      17   2   7091   0   5   4   7   1   4   1    0   0  29  37
7      46   4   2342  14  14   2   9   0   4   1   44   0  31  37
8       7   2  11153  15   9   4   7   4   4   0    0   0  39  37
9      38   2   2361   5   3   2   2   0   4   1    0   0   9  37
10     48   2   6199  11   8   2   6   0   4   1   77   0  39  37
11     19   0   7773   9  12   2   0   0   4   1    0   0  39  37
12      9   2   1548  11   8   4   0   1   4   0    0   0  38  37
14     31   2   9790  11   8   2   6   0   4   1   44   0  47  37
15     26   2  10882  12  13   2   3   0   4   1    0   0  49  37
16      3   5  11624  15   9   4   7   3   4   1    0   0  24  37
17     26   2   3425  11   8   2   0   5   4   0    0   0  29  37
18     20   2   1093  11   8   6   6   4   4   0    0   0  19  37
20     17   2   2508   9  12   2  12   0   4   1    0   0  46  37
21     17   2   8718  15   9   4   7   3   2   0    0   0  34  37
23      8   2   8107   9  12   4   9   1   4   1    0   0  42  27
24      8   2   7488   9  12   2   9   0   4   1    0   0  39  37
25     28   4  11575  11   8   2   2   0   4   1   84   0  84  37
26      5   2   8648  11   8   4   0   3   4   1    0   0  19  37
27      6   2   3666  11   8   5   6   4   2   1    0   0  53  37
28     37   2   2092  11   8   2   2   0   4   1    0   0  34  37
29     15   4   2574  15   9   4   9   1   4   1    0   0  59  37
30     29   5   2430  15   9   2   3   0   2   1   87   0  37  37
31     39   4   6335   1   6   6   7   4   4   0    0   0  49  37
32      7   4   6452   9  12   4  11   1   4   1    0   0  49  37
33      6   1   9267  15   9   2  10   0   4   1    0   0  39  37
34      9   2    640  11   8   0   3   4   4   0    0   0  39  37
...    ..  ..    ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..
16248   8   2   8822  11   8   0   6   1   2   1    0   0  39  37
16249  14   2   2709  11   8   4   6   1   4   1    0   0  39  37
16250  32   3   1436  11   8   2   3   0   4   1    0   0  39   1
16252  43   2   3009   8  10   2   9   0   4   1   87   0  39  37
16253  22   2   8429   9  12   4  12   1   4   0    0  27  39  37
16254  21   2   4270  12  13   2   9   0   4   1    0   0  49  37
16255  26   1     51  12  13   2   3   0   4   1    0  42  49  37
16256   6   2   1870  11   8   4   6   3   4   1    0   0  39  37
16257  56   3   4751  15   9   0   3   1   4   0    0   0  39  37
16258  18   2   5733  15   9   2  10   0   4   1    0   0  39  37
16259  49   2  10860  11   8   6  11   2   4   0    0   0   7  37
16260  10   2  11565  15   9   4  11   1   4   0    0   0  44  37
16261  23   2   7310  14  14   2   9   0   4   1  101   0  54  37
16262  34   2   1563  11   8   2   2   0   4   1    0   0  39  37
16263   5   2   9562  15   9   4   2   3   4   1    0   0  39  37
16264  47   4   3745  11   8   6   4   1   4   1    0   0  31  37
16266  38   2   8237  11   8   5   8   1   4   0    0   0  31  37
16267  21   2   8985   8  10   4   0   4   2   0    0   0  39  37
16268  41   2  10042   7  11   0   9   1   4   1    0   0  35  37
16269  15   2   5485  11   8   2   5   0   4   1    0   0  39  37
16270  31   2   9901  11   8   2   0   0   4   1    0   0  39  37
16271  44   2   1749  11   8   2  11   0   4   1    0   0  47  37
16272  14   2  11608  11   8   2   2   0   4   1    0   0  39  37
16273   8   2  10942  11   8   4   7   3   4   0    0   0  39  37
16274  31   1  10923  12  13   0   7   1   4   1    0   0  39  37
16275  16   2   8927   9  12   4   9   3   4   1    0   0  39  37
16276  22   2   7893   9  12   0   9   1   4   0    0   0  35  37
16278  21   2  11193   9  12   2   9   0   4   1    0   0  49  37
16279  27   2   1593   9  12   0   0   3   1   

###### Ahora, se crea el clasificador para la técnica de K-Vecinos más cercanos y se evalúa el desempeño del clasificador.

In [47]:
################################################################
##################  K-Vecinos más cercanos #####################
################################################################

n_neighbors = 21
KNN = KNeighborsClassifier(n_neighbors)
KNN.fit(x_train, y_train)
KNN_predict = KNN.predict(x_test)

print("\n############## Accuracy KNN ##################")
print(metrics.accuracy_score(y_test, KNN_predict))
print(metrics.confusion_matrix(y_test, KNN_predict))


############## Accuracy KNN ##################
0.7903718459495352
[[11141   219]
 [ 2938   762]]


###### Ahora, se crea el clasificador para las técnicas de Análisis de discriminante lineal y se evalúa el desempeño del clasificador.

In [9]:
################################################################
#############  Análisis de discriminante lineal ################
################################################################

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(x_train, y_train)

y_predl = lda.predict(x_test)
print("\n############## Accuracy LDA ##################")
print(metrics.accuracy_score(y_test, y_predl))
print(metrics.confusion_matrix(y_test, y_predl))



################################################################
############  Análisis de discriminante cuadrático #############
################################################################

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda = QuadraticDiscriminantAnalysis()
qda.fit(x_train, y_train)

y_predd = qda.predict(x_test)
print("\n############## Accuracy QDA ##################")
print(metrics.accuracy_score(y_test, y_predd))
print(metrics.confusion_matrix(y_test, y_predd))


############## Accuracy LDA ##################
0.8177954847277557
[[10798   562]
 [ 2182  1518]]

############## Accuracy QDA ##################
0.8200531208499336
[[10549   811]
 [ 1899  1801]]
